#!/usr/bin/env node
/**
 * sync-gumroad.mjs — pulls published products from the Gumroad API
 * and writes src/data/products.json for the shop page.
 *
 * Usage:
 *   GUMROAD_ACCESS_TOKEN=xxx node scripts/sync-gumroad.mjs
 *
 * Token: Gumroad → Settings → Advanced → Applications → create app →
 * "Generate access token" (Redirect URI: http://127.0.0.1).
 *
 * Intended to run on Hermes, triggered via Telegram, then commit + push:
 *   node scripts/sync-gumroad.mjs && git add src/data/products.json \
 *     && git commit -m "sync: gumroad products" && git push
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const TOKEN = process.env.GUMROAD_ACCESS_TOKEN;
if (!TOKEN) {
  console.error('Missing GUMROAD_ACCESS_TOKEN');
  process.exit(1);
}

const res = await fetch('https://api.gumroad.com/v2/products', {
  headers: { Authorization: `Bearer ${TOKEN}` },
});
if (!res.ok) {
  console.error(`Gumroad API error: ${res.status} ${await res.text()}`);
  process.exit(1);
}
const data = await res.json();
if (!data.success) {
  console.error('Gumroad API returned success=false');
  process.exit(1);
}

const NEW_WINDOW_DAYS = 30;
const now = Date.now();

const products = data.products
  .filter((p) => p.published && !p.deleted)
  .map((p, i) => {
    const priceEuro = (p.price / 100).toFixed(p.price % 100 === 0 ? 0 : 2);
    const url = p.short_url || `https://technosupps.gumroad.com/l/${p.custom_permalink || p.id}`;
    const created = p.created_at ? Date.parse(p.created_at) : 0;
    return {
      id: p.custom_permalink || p.id,
      cat: `PACK · ${String(data.products.length - i).padStart(3, '0')}`,
      title: p.name,
      sub: p.custom_summary || 'Dub Techno Producer Tool',
      price: `€${priceEuro}`,
      fmt: 'Digital Download',
      description: (p.description || '').replace(/<[^>]+>/g, '').slice(0, 300),
      url,
      checkoutUrl: `${url}?wanted=true`,
      cover: p.thumbnail_url || p.preview_url || null,
      new: created > 0 && now - created < NEW_WINDOW_DAYS * 24 * 3600 * 1000,
    };
  });

const out = {
  _note: 'Generated by scripts/sync-gumroad.mjs — do not edit by hand.',
  updated: new Date().toISOString(),
  products,
};

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
writeFileSync(join(root, 'src/data/products.json'), JSON.stringify(out, null, 2) + '\n');
console.log(`Synced ${products.length} products.`);
